-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE * OP.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE OP
ON P.PRODUCT_ID = OP.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;
