-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.NAME
# SELECT *
FROM ANIMAL_OUTS AO
LEFT OUTER JOIN ANIMAL_INS AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL;
# WHERE AI.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS);