-- 코드를 입력하세요 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
SELECT GB.TITLE, GB.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, DATE_FORMAT(GR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD GB
JOIN USED_GOODS_REPLY GR
ON GB.BOARD_ID = GR.BOARD_ID
WHERE GB.CREATED_DATE LIKE '2022-10-%'
ORDER BY GR.CREATED_DATE, GB.TITLE;

